Models/Alojamiento.cs
using System;

namespace cadenaHotelera.Models
{
    public class Alojamiento
    {
        public int id { get; set; }
        public int habitacionId { get; set; }
        public string fecha_inicial { get; set; }
        public string fecha_final { get; set; }
        public string hora_inicial { get; set; }
        public string hora_final { get; set; }
        public DateTime EnrollmentDate { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace cadenaHotelera.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Habitacion.cs
using System;

namespace cadenaHotelera.Models
{
    public class Habitacion
    {
        public int id { get; set; }
        public int sedeId { get; set; }
        public string tipo { get; set; }
        public int cupo { get; set; }
        public string disponibilidad { get; set; }
        public DateTime EnrollmentDate { get; set; }
    }
}

Models/Sede.cs
using System;

namespace cadenaHotelera.Models
{
    public class Sede
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public int cantidadHabitaciones { get; set; }
        public string temporada { get; set; }
        public DateTime EnrollmentDate { get; set; }
    }
}

Controllers/HomeController.cs
using cadenaHotelera.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace cadenaHotelera.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/SedesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using cadenaHotelera.Data;
using cadenaHotelera.Models;

namespace cadenaHotelera.Controllers
{
    public class SedesController : Controller
    {
        private readonly cadenaHoteleraContext _context;

        public SedesController(cadenaHoteleraContext context)
        {
            _context = context;
        }

        // GET: Sedes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Sede.ToListAsync());
        }

        // GET: Sedes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sede = await _context.Sede
                .FirstOrDefaultAsync(m => m.id == id);
            if (sede == null)
            {
                return NotFound();
            }

            return View(sede);
        }

        // GET: Sedes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Sedes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,nombre,cantidadHabitaciones,temporada,EnrollmentDate")] Sede sede)
        {
            if (ModelState.IsValid)
            {
                _context.Add(sede);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(sede);
        }

        // GET: Sedes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sede = await _context.Sede.FindAsync(id);
            if (sede == null)
            {
                return NotFound();
            }
            return View(sede);
        }

        // POST: Sedes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,nombre,cantidadHabitaciones,temporada,EnrollmentDate")] Sede sede)
        {
            if (id != sede.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sede);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SedeExists(sede.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(sede);
        }

        // GET: Sedes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sede = await _context.Sede
                .FirstOrDefaultAsync(m => m.id == id);
            if (sede == null)
            {
                return NotFound();
            }

            return View(sede);
        }

        // POST: Sedes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var sede = await _context.Sede.FindAsync(id);
            _context.Sede.Remove(sede);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SedeExists(int id)
        {
            return _context.Sede.Any(e => e.id == id);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Sedes/Create.cshtml
@model cadenaHotelera.Models.Sede

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Sede</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="nombre" class="control-label"></label>
                <input asp-for="nombre" class="form-control" />
                <span asp-validation-for="nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="cantidadHabitaciones" class="control-label"></label>
                <input asp-for="cantidadHabitaciones" class="form-control" />
                <span asp-validation-for="cantidadHabitaciones" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="temporada" class="control-label"></label>
                <input asp-for="temporada" class="form-control" />
                <span asp-validation-for="temporada" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EnrollmentDate" class="control-label"></label>
                <input asp-for="EnrollmentDate" class="form-control" />
                <span asp-validation-for="EnrollmentDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Sedes/Delete.cshtml
@model cadenaHotelera.Models.Sede

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Sede</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.cantidadHabitaciones)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.cantidadHabitaciones)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.temporada)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.temporada)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EnrollmentDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EnrollmentDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Sedes/Details.cshtml
@model cadenaHotelera.Models.Sede

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Sede</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.cantidadHabitaciones)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.cantidadHabitaciones)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.temporada)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.temporada)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EnrollmentDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EnrollmentDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Sedes/Edit.cshtml
@model cadenaHotelera.Models.Sede

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Sede</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="nombre" class="control-label"></label>
                <input asp-for="nombre" class="form-control" />
                <span asp-validation-for="nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="cantidadHabitaciones" class="control-label"></label>
                <input asp-for="cantidadHabitaciones" class="form-control" />
                <span asp-validation-for="cantidadHabitaciones" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="temporada" class="control-label"></label>
                <input asp-for="temporada" class="form-control" />
                <span asp-validation-for="temporada" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EnrollmentDate" class="control-label"></label>
                <input asp-for="EnrollmentDate" class="form-control" />
                <span asp-validation-for="EnrollmentDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Sedes/Index.cshtml
@model IEnumerable<cadenaHotelera.Models.Sede>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.cantidadHabitaciones)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.temporada)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EnrollmentDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cantidadHabitaciones)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.temporada)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EnrollmentDate)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cadena Hotelera</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">cadenaHotelera</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sedes" asp-action="Index">Sede</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - cadenaHotelera - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>